### PR TITLE
fix - authButton Functionality and optimise code

### LINKED ISSUE #50: [BUG] Logged in user's username not showing in pages other than **home** page, not showing logout prompt on clicking.
### Description

Not rendering the signup/login pages when clicking the button from pages other than **Home** page.
After logging in, only home page's login/signup button on header is changing to user's username.  
All other main pages such as about, contacts and other pages still showing only the login/signup button.  
Also when clicking the username button on home page while already logged in, it's asking to logout. It's not asking in any other page.  
I want to fix the issue.  

### Screenshots

Home page
Ezyshoping home page
Ezyshoping home page logout prompt

Other pages
Ezyshoping about page
Ezyshoping contacts page

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by muhafiz5814**
Fixes #50 

**Changes Description**
After logging in every page is showing the `username` instead of `login/signup` button.
On clicking the `username` button asking the confirmation for `logout`.
After logging out, user is sent to home page instead of reloading the current page.
Enhanced the code by removing unnecessary lines of code.

**Steps taken**
Moved the authorization logic from index.html to a separate script file to implement code reusability.
Then added that script file in each page instead of writing whole login in each page's html.
For more info see the reviews on code.

**Video of Changes**

https://github.com/user-attachments/assets/8d4a7398-db1a-4895-8511-71c00a560e69

Comment if you want any modification in changes.

### CODE REVIEW

**Comment by mdazfar2** [comment]
@muhafiz5814 update sync fork and let me know

File: RegisterPages/register.js [hunk 1]
```diff
@@ -128,9 +128,9 @@ loginForm.addEventListener('submit', function (event) {
 
     // Check if credentials match
     if (storedUser && loginUsername === storedUser.username && loginPassword === storedUser.password) {
-        alert('Login successful! Redirecting to home page...'); // Notify user
         localStorage.setItem('currentUser', loginUsername); // Store the current user's username
-        window.location.href = "../index.html"; // Redirect to home page
+        alert('Login successful!'); // Notify user of successfull login.
+        history.back(); //  Return back to the page, from where user requested login.
```
Comment (muhafiz5814) [inline RegisterPages/register.js:133]: Instead of sending the user to home page after login, user is sent back to the page from where it requested login.

File: index.html [hunk 2]
```diff
@@ -622,38 +622,9 @@ <h3 class="text-primary mb-4">Newsletter</h3>
     <!-- Template Javascript -->
     <script src="js/main.js"></script>
 
-    <script>
```
Comment (muhafiz5814) [inline index.html:625]: This code has been moved in a separate file `auth.js` with some optimisations.

File: js/auth.js [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+
+      if (confirmLogout) {
+          // If confirmed, remove the current user from localStorage
+          localStorage.removeItem('currentUser');
+          // Go to the home page."
+          location.href = "index.html";
+      }
+    });
+  }
+});
```
Comment (muhafiz5814) [inline js/auth.js:24]: Logout functionality has been moved inside the `if` statement.

File: index.html (hunk 2 above)
Comment (mdazfar2) [reply index.html:625]: @muhafiz5814 do what you want.

**Review by thakuratul2 — CHANGES_REQUESTED** [review]
@muhafiz5814 remove the comments

File: RegisterPages/register.js (hunk 1 above)
Comment (muhafiz5814) [reply RegisterPages/register.js:133]: @mdazfar2 Okay!

**Comment by muhafiz5814** [comment]
> @muhafiz5814 update sync fork and let me know

@mdazfar2 done and everything working fine, You want me to wait until issue #8 completes or you are going to merge.

**Comment by muhafiz5814** [comment]
> @muhafiz5814 remove the comments

@thakuratul2 Do you want me to remove all the comments I made in code review ?

**Comment by mdazfar2** [comment]
@muhafiz5814 fix the image on the landing page to be centered, making it look good and attractive and update sync fork again

{7C0886CF-DFED-4438-B3BC-6096BA9AA207}

**Comment by muhafiz5814** [comment]
> @muhafiz5814 fix the image on the landing page to be centered, making it look good and attractive and update sync fork again
> 
> {7C0886CF-DFED-4438-B3BC-6096BA9AA207}

@mdazfar2 Okay, I will try and inform you soon.

**Comment by mdazfar2** [comment]
Alright!

**Comment by muhafiz5814** [comment]
@mdazfar2 top of the hero section image have been fixed.
I also tried to reduced the height of the section, you can check it out here.

https://github.com/user-attachments/assets/d17379a3-c06e-48d9-8015-fabc49e14eb2

if you like to keep the reduced size change, I can commit the changes. otherwise I already have committed the image issue and it is fixed now.

waiting for your response.

**Comment by mdazfar2** [comment]
@muhafiz5814 only the image i will tell for fix you are changed whole landing page which looks weird

**Comment by muhafiz5814** [comment]
@mdazfar2 as I said, reducing the size of the hero section was only to get a confirmation, I have not committed any changes regarding that.
However image have been fixed as you can see in the screenshot.

**Review by mdazfar2 — APPROVED** [review]
Amazing!

**Comment by mdazfar2** [comment]
@muhafiz5814 Checkout the issue #159 if you want to work on it.
